# Configuraci贸n de Netlify para el Infograma UIDH

[build]
  publish = "."

# Configuraci贸n para redirecciones y encabezados
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuraci贸n de redirecci贸n para URLs limpias
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
